=== OlgaPerolainen/HTML-CSS-XML/XML-Lab/resume_complex.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:group name="person">
	<xs:sequence>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="lastname" type="xs:string"/>
		<xs:element name="fathersname" type="xs:string"/>
		<xs:element name="age" type="ageType"/>
		<xs:element name="workplace" type="xs:string"/>
		<xs:element name="post" type="xs:string"/>
		<xs:element name="dateOfBirth">
			<xs:simpleType>
				<xs:restriction base="xs:date">
					<xs:minInclusive value="1947-01-01"/>
					<xs:maxInclusive value="1992-01-01"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="education">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="высшее"/>
					<xs:enumeration value="среднее"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="address" type="xs:string"/>
		<xs:element name="phone">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]"></xs:pattern>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="familystatus">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="женат"/>
					<xs:enumeration value="не женат"/>
					<xs:enumeration value="замужем"/>
					<xs:enumeration value="не замужем"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="desiredSalary">
			<xs:complexType>
					<xs:simpleContent>
						<xs:extension base = "xs:int">
							<xs:attribute name = "currency" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:group>

<xs:simpleType name="ageType">
	<xs:restriction base="xs:int">
		<xs:minInclusive value="20"/>
		<xs:maxInclusive value="65"/>
	</xs:restriction>
</xs:simpleType>

<xs:element name="resume">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="higherEducation">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="candidate" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:group ref="person"/>
								</xs:sequence>
								<xs:attribute name="id"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="secondaryEducation">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="candidate" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:group ref="person"/>
								</xs:sequence>
								<xs:attribute name="id"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== OlgaPerolainen/HTML-CSS-XML/XML-Lab/resume_complex.xml
<?xml version="1.0" encoding="UTF-8"?>
<resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/wwwol/Downloads/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/%D0%9A%D1%83%D1%80%D1%81/HTML-XML/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B/XML-Lab01/resume_complex.xsd">
    <higherEducation>
		<candidate id="a">
			<name>Елена</name>
			<lastname>Иванова</lastname>
			<fathersname>Васильевна</fathersname>
			<age>31</age>
			<workplace>OOO "Проект"</workplace>
			<post>менеджер</post>
			<dateOfBirth>1990-08-10</dateOfBirth>
			<education>высшее</education>
			<address>СПб, Московский проспект, д.183</address>
			<phone>123-45-67</phone>
			<familystatus>замужем</familystatus>
			<desiredSalary currency="RUR">50000</desiredSalary>
		</candidate>

		<candidate id="b">
			<name>Виктор</name>
			<lastname>Иванов</lastname>
			<fathersname>Андреевич</fathersname>
			<age>33</age>
			<workplace>OOO "Проект"</workplace>
			<post>экономист</post>
			<dateOfBirth>1989-01-15</dateOfBirth>
			<education>высшее</education>
			<address>СПб, Московский проспект, д.183</address>
			<phone>123-45-68</phone>
			<familystatus>женат</familystatus>
			<desiredSalary currency="RUR">60000</desiredSalary>
		</candidate>																										
	</higherEducation>
    
	<secondaryEducation>
		<candidate id="c">
			<name>Людмила</name>
			<lastname>Сидорова</lastname>
			<fathersname>Валентиновна</fathersname>
			<age>39</age>
			<workplace>OOO "Строй"</workplace>
			<post>менеджер по продажам</post>
			<dateOfBirth>1982-10-22</dateOfBirth>
			<education>среднее</education>
			<address>СПб, Ленинский проспект, д.109</address>
			<phone>123-45-60</phone>
			<familystatus>не замужем</familystatus>
			<desiredSalary currency="RUR">40000</desiredSalary>
		</candidate>
	</secondaryEducation>
</resume>
